### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by sauron** [edelpero/action_parameter#1]
Hey @edelpero,

Great work on this.
This is simple a _suggestion_ instead of an issue.
My suggestion is to add on the examples the before and after of using this gem.
Something like "You use to do ... but with action_parameter you simply have to ..."
In that way it is easier to understand how this gems really works.

Sorry for not sending a pull request on this(which I would love to do), but I'm really bussy right now.

Best.

**Comment by edelpero** [comment]
Thank you @sauron. You're right, thanks for your suggestion. :)

**Comment by edelpero** [comment]
Let me know what you think about it now @sauron. :) Thanks again.

**Comment by sauron** [comment]
Much better, thank you!
